

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: postgres
    ports:
      - "5001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: 